<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
//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


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.sendinblue.com/v3/emailCampaigns');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \n# Define the campaign settings \n\"name\":\"Campaign sent via the API\", \n\"subject\":\"My subject\", \n\"sender\": { \"name\": \"From name\", \"email\":\"faridpn1353@gmail.com\" }, \n\"type\": \"classic\", \n# Content that will be sent \n\"htmlContent\": \"Congratulations! You successfully sent this example campaign via the Sendinblue API.\", \n# Select the recipients\n\"recipients\": { \"listIds\": [2,7] }, \n# Schedule the sending in one hour\n\"scheduledAt\": \"2018-01-01 00:00:01\", \n}");

$headers = array();
$headers[] = 'Api-Key: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';
$headers[] = 'Content-Type:application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);


print_r($result)

?>